version: 2.1
orbs:
  android: circleci/android@2.4.0
jobs:
  build:
    docker:
      - image: cimg/android:2023.11.1
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Create Local Properties
          command: echo "sdk.dir=$ANDROID_HOME" > local.properties
      - run:
          name: Accept Android SDK Licenses
          command: (yes || true) | sdkmanager --licenses
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew assembleFreeDebug
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs/apk/free/debug/
          destination: artifact-file
      - run:
          name: Install Firebase CLI
          command: curl -sL https://firebase.tools | bash
      - run:
          name: Upload to Firebase App Distribution
          command: |
            firebase appdistribution:distribute app/build/outputs/apk/free/debug/app-free-debug.apk \
              --app $FIREBASE_APP_ID_FREE_DEBUG \
              --token $FIREBASE_TOKEN \